name: windows-build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        arch: ["x64", "x86"]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: build
      run: ./Build.bat
      
    - name: check dir
      run: |
        tree
        dir build/
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x86
      
    - name: msbuild
      run: |
        cd build
        msbuild atsplugin.sln -p:Configuration=Release -m -t:${{ matrix.arch }}.
      
    - name: check dir
      run: |
        tree
        dir build/
        dir build/Release/
        dir build/

    - name: collect staging built files
      run: mv build/Release/atsplugin.dll atsplugin_${{ matrix.arch }}.dll

    - name: upload built files
      uses: actions/upload-artifact@v3
      with:
        name: built
        path: atsplugin_${{ matrix.arch }}.dll
