name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: build
      run: ./Build.bat
      
    - name: dir
      run: dir
      
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./*
